channels:
- conda-forge
dependencies:
- python=3.9.19
- pip<=25.2
- pip:
  - mlflow==2.22.1
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - psutil==7.0.0
  - scikit-learn==1.0.2
  - scipy==1.13.1
name: mlflow-env
