# run "docker-compose -f docker-compose.local.yaml up -d" before pre-committing
# and create a Kinesis stream "aws --endpoint-url=http://localhost:4566 kinesis create-stream --stream-name stg_taxi_predictions --shard-count 1"
# or comment out all pytests
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        exclude: ^template\.yaml$|^.*\.cf\.yaml$
    -   id: check-added-large-files
-   repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
    -   id: isort
-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black
        language_version: python3.9
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: ["-rn", "-sn", "--recursive=y"]
#    -   id: pytest-check
#        name: pytest-check
#        entry: pytest
#        language: system
#        pass_filenames: false
#        always_run: true
#        args: ["tests/"]
