# docker-compose.yaml for Taxi Duration Prediction MLOps Project
# Supports both LocalStack (local dev/test) and AWS (test/prod) via environment variables.
# Use .env.dev for LocalStack, .env.prod for AWS, or .env.stg for staging.

version: "3.8"

services:
  backend:
    image: ${LOCAL_IMAGE_NAME}
    ports:
      - "8080:8080"
    environment:
      - PREDICTIONS_STREAM_NAME=${PREDICTIONS_STREAM_NAME}
      - RUN_ID=${RUN_ID}
      - AWS_DEFAULT_REGION=${AWS_REGION}
      - MODEL_LOCATION=/app/model
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - MODEL_BUCKET=${MODEL_BUCKET}
      # For LocalStack, set KINESIS_ENDPOINT_URL and MLFLOW_S3_ENDPOINT_URL in .env.dev
      - KINESIS_ENDPOINT_URL=${KINESIS_ENDPOINT_URL}
      - MLFLOW_S3_ENDPOINT_URL=${MLFLOW_S3_ENDPOINT_URL}
    volumes:
      - "./model:/app/model"
    depends_on:
      - kinesis
      - localstack

  # LocalStack for local development/testing (Kinesis, S3, Lambda, etc.)
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=kinesis,s3,lambda
      - DEFAULT_REGION=${AWS_REGION}
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./localstack-data:/tmp/localstack/data

  # Alias for Kinesis endpoint (for legacy/test scripts)
  kinesis:
    image: localstack/localstack
    ports:
      - "4567:4566"
    environment:
      - SERVICES=kinesis
      - DEFAULT_REGION=${AWS_REGION}
    command: ["localstack", "start", "-d"]

# Usage:
# - For LocalStack/local dev: use .env.dev and keep localstack/kinesis services enabled.
# - For AWS deployment: use .env.prod, comment out/remove localstack/kinesis services, and do NOT set KINESIS_ENDPOINT_URL/MLFLOW_S3_ENDPOINT_URL (let boto3 use AWS defaults).
# - For deployment test/staging: use .env.stg and adjust as needed.
#
# Example .env.dev:
#   MODEL_BUCKET=mlflow-models-rll
#   PREDICTIONS_STREAM_NAME=stg_taxi_predictions
#   RUN_ID=Test123
#   AWS_REGION=eu-north-1
#   AWS_ACCESS_KEY_ID=test
#   AWS_SECRET_ACCESS_KEY=test
#   KINESIS_ENDPOINT_URL=http://localstack:4566
#   MLFLOW_S3_ENDPOINT_URL=http://localstack:4566
#
# Example .env.prod:
#   MODEL_BUCKET=mlflow-models-rll-mlops-capstone
#   PREDICTIONS_STREAM_NAME=prod_taxi_predictions
#   RUN_ID=your-prod-run-id
#   AWS_REGION=eu-north-1
#   AWS_ACCESS_KEY_ID=your-prod-key
#   AWS_SECRET_ACCESS_KEY=your-prod-secret
#
# Docker Compose will automatically substitute variables from the active .env file.