# Use .env.dev for local development with LocalStack.
version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: terraform/Dockerfile
    image: ${LOCAL_IMAGE_NAME}
    ports:
      - "8080:8080"
    environment:
      AWS_REGION: ${AWS_REGION}
      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI}
      PREDICTIONS_STREAM_NAME: ${PREDICTIONS_STREAM_NAME}
      RUN_ID: ${RUN_ID}
      AWS_DEFAULT_REGION: ${AWS_REGION}
      MODEL_LOCATION: /app/model
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      MODEL_BUCKET: ${MODEL_BUCKET}
      KINESIS_ENDPOINT_URL: ${KINESIS_ENDPOINT_URL}
      MLFLOW_S3_ENDPOINT_URL: ${MLFLOW_S3_ENDPOINT_URL}
    volumes:
      - "./model:/app/model"
      - "./.env.dev:/app/.env.dev"
      - "./.env.dev:/var/task/.env.dev"
      # Mount event.json to both possible paths used by tests
      - "./tests/integration/event.json:/var/task/tests/integration/event.json"
      - "./tests/integration/event.json:/var/task/integration-test/event.json"
    depends_on:
      - localstack
      - mlflow

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      SERVICES: kinesis,s3,lambda
      DEFAULT_REGION: ${AWS_REGION}
      DATA_DIR: /tmp/localstack/data

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5000:5000"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      MLFLOW_S3_ENDPOINT_URL: ${MLFLOW_S3_ENDPOINT_URL}
    command: /bin/sh -c "pip install boto3 && mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root s3://${MODEL_BUCKET}/ --host 0.0.0.0 --port 5000"