version = 0.1

[default.deploy.parameters]
stack_name = "y"
resolve_s3 = true
s3_prefix = "y"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "ModelBucket=\"rll-models-prod\" RunId=\"a986756f70a240cf8808a59ed77ba2d3\" PredictionsStreamName=\"prod_taxi_predictions\""
image_repositories = []
