# template.yaml - AWS SAM template for taxi duration prediction application
# Environment separation:
#   - For development, use .env.dev (MODEL_BUCKET: your-dev-bucket)
#   - For production, use .env.prod (MODEL_BUCKET: your-prod-bucket)
# MODEL_BUCKET and related values are set via Parameters and environment variables for flexibility.

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  ModelBucket:
    Type: String
    Default: your-model-bucket
    Description: S3 bucket for ML models (use your-dev-bucket for dev, your-prod-bucket for prod)
  RunId:
    Type: String
    Default: your-run-id
    Description: MLflow run ID (set via .env.dev or .env.prod)
  PredictionsStreamName:
    Type: String
    Default: stg_taxi_predictions
    Description: Kinesis stream for predictions (stg_taxi_predictions for dev, prod_taxi_predictions for prod)

Resources:
  RideDurationPredictionFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: <your-account-id>.dkr.ecr.<your-region>.amazonaws.com/taxi-duration-lambda:latest
      Timeout: 10
      MemorySize: 128 # Change for better performance
      Environment:
        Variables:
          MODEL_BUCKET: !Ref ModelBucket
          RUN_ID: !Ref RunId
          PREDICTIONS_STREAM_NAME: !Ref PredictionsStreamName
      Events:
        KinesisTrigger:
          Type: Kinesis
          Properties:
            Stream: !Sub "arn:aws:kinesis:${AWS::Region}:${AWS::AccountId}:stream/${PredictionsStreamName}"
            StartingPosition: LATEST