# template.yaml - AWS SAM template for taxi duration prediction application
# Environment separation: 
#   - For development, use .env.dev (MODEL_BUCKET: rll-models-dev)
#   - For production, use .env.prod (MODEL_BUCKET: rll-models-prod)
# MODEL_BUCKET and related values are set via Parameters and environment variables for flexibility.

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  ModelBucket:
    Type: String
    Default: rll-models-dev
    Description: S3 bucket for ML models (use rll-models-dev for dev, rll-models-prod for prod)
  RunId:
    Type: String
    Default: your-run-id
    Description: MLflow run ID (set via .env.dev or .env.prod)
  PredictionsStreamName:
    Type: String
    Default: stg_taxi_predictions
    Description: Kinesis stream for predictions (stg_taxi_predictions for dev, prod_taxi_predictions for prod)

Resources:
  RideDurationPredictionFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: 887329216606.dkr.ecr.eu-north-1.amazonaws.com/taxi-duration-lambda:v2
      Timeout: 30
      MemorySize: 256 # Changed from 128 to 256 for better performance
      Environment:
        Variables:
          MODEL_BUCKET: !Ref ModelBucket
          RUN_ID: !Ref RunId
          PREDICTIONS_STREAM_NAME: !Ref PredictionsStreamName