# config/grafana_datasources.yaml
# This file is used to configure Grafana data sources for Evidently Dashboards.
# Environment separation: Uses .env.dev for development, .env.prod for production.
# All database, bucket, and endpoint values should be loaded from environment variables for flexibility.
# For Docker Compose, these values should match the environment variables in your .env.dev/.env.prod files.

apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: ${DB_HOST}:${DB_PORT} # Loaded from environment (.env.dev/.env.prod)
    database: ${DB_NAME}       # Loaded from environment (.env.dev/.env.prod)
    user: ${DB_USER}           # Loaded from environment (.env.dev/.env.prod)
    secureJsonData:
      password: ${DB_PASSWORD} # Loaded from environment (.env.dev/.env.prod)
    jsonData:
      sslmode: 'disable'

# Example .env.dev/.env.prod entries:
# DB_HOST=db
# DB_PORT=5432
# DB_NAME=test
# DB_USER=postgres
# DB_PASSWORD=example

# For S3 or other buckets, add additional data sources here and use environment variables for bucket names and endpoints.