name: CD-Deploy
on:
  push:
    branches:
      - 'main'

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "eu-north-1"

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: TF plan
        id: tf-plan
        working-directory: terraform
        run: |
          terraform init -backend-config="key=mlops-capstone-prod.tfstate" -reconfigure && terraform plan -var-file=vars/prod.tfvars

      - name: TF Apply
        id: tf-apply
        working-directory: terraform
        if: ${{ steps.tf-plan.outcome }} == 'success'
        run: |
          terraform apply -auto-approve -var-file=vars/prod.tfvars
          echo "::set-output name=ecr_repo::$(terraform output ecr_repo | xargs)"
          echo "::set-output name=predictions_stream_name::$(terraform output predictions_stream_name | xargs)"
          echo "::set-output name=model_bucket::$(terraform output model_bucket | xargs)"
          echo "::set-output name=lambda_function::$(terraform output lambda_function | xargs)"

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image-step
        working-directory: terraform
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ steps.tf-apply.outputs.ecr_repo }}
          IMAGE_TAG: "latest"
        run: |
          docker build -t ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image_uri::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

      - name: Get model artifacts
        id: get-model-artifacts
        env:
          MODEL_BUCKET_DEV: "mlflow-models-rll-mlops-capstone"
          MODEL_BUCKET_PROD: ${{ steps.tf-apply.outputs.model_bucket }}
        run: |
          export LATEST_KEY=$(aws s3api list-objects-v2 --bucket ${MODEL_BUCKET_DEV} \
            --prefix "1/" \
            --query 'sort_by(Contents, &LastModified)[?contains(Key, `artifacts/model/MLmodel`)] | [-1].Key' --output=text)
          echo "Latest model key: $LATEST_KEY"
          export RUN_ID=$(echo "$LATEST_KEY" | cut -f2 -d/)
          echo "Extracted RUN_ID: $RUN_ID"
          if [ -z "$RUN_ID" ]; then
            echo "No RUN_ID found! Check that your S3 bucket has model artifacts under 1/<run_id>/artifacts/model/MLmodel"
            exit 1
          fi
          aws s3 sync s3://${MODEL_BUCKET_DEV} s3://${MODEL_BUCKET_PROD}
          echo "run_id=${RUN_ID}" >> $GITHUB_OUTPUT

      - name: Update Lambda
        env:
          LAMBDA_FUNCTION: ${{ steps.tf-apply.outputs.lambda_function }}
          PREDICTIONS_STREAM_NAME: ${{ steps.tf-apply.outputs.predictions_stream_name }}
          MODEL_BUCKET: ${{ steps.tf-apply.outputs.model_bucket }}
          RUN_ID: ${{ steps.get-model-artifacts.outputs.run_id }}
        run: |
          if [ -z "$RUN_ID" ]; then
            echo "RUN_ID is empty, skipping Lambda update."
            exit 1
          fi

          STATE=$(aws lambda get-function --function-name $LAMBDA_FUNCTION --region "eu-north-1" --query 'Configuration.LastUpdateStatus' --output text)
          while [[ "$STATE" == "InProgress" ]]
          do
              echo "sleep 5sec ...."
              sleep 5s
              STATE=$(aws lambda get-function --function-name $LAMBDA_FUNCTION --region "eu-north-1" --query 'Configuration.LastUpdateStatus' --output text)
              echo $STATE
          done

          aws lambda update-function-configuration --function-name $LAMBDA_FUNCTION \
            --environment Variables={\"PREDICTIONS_STREAM_NAME\":\"$PREDICTIONS_STREAM_NAME\",\"MODEL_BUCKET\":\"$MODEL_BUCKET\",\"RUN_ID\":\"$RUN_ID\"}